### ISSUE TITLE
[BUG]添加本地音乐文件夹后，点击浏览本地音乐出现程序未响应

### ISSUE THREAD

**Issue by Andrea-lyz** [Miaoyww/NonsPlayer#62]
**Describe the bug**
添加本地音乐文件夹后，点击浏览本地音乐出现程序未响应
曲目数量大概1000+
**To Reproduce**
添加本地音乐文件夹后，点击浏览本地音乐出现程序未响应

**Expected behavior**
正常加载曲目列表

**Screenshots**
![image](https://github.com/user-attachments/assets/b1e173ca-7fef-44e5-b1e6-2bf69c50b180)

**Desktop (please complete the following information):**
 - OS: 
处理器	AMD Ryzen 7 8845H w/ Radeon 780M Graphics   3.80 GHz
机带 RAM	32.0 GB (27.8 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 11 专业工作站版
版本号	24H2
安装日期	‎2024/‎9/‎25
操作系统版本	26100.1876
体验	Windows Feature Experience Pack 1000.26100.23.0
 - Version [e.g. 0.2.6]
app-0.5.52

**Comment by Andrea-lyz** [comment]
相关错误log
`[22:47:00.233] [INFO] []: System: Microsoft Windows NT 10.0.26100.0
[22:47:00.236] [INFO] []: Command Line: D:\NonsPlayer\app-0.5.52\NonsPlayer.dll
[22:47:00.304] [INFO] []: Start loading config, current config path:C:\Users\Andrea-TB\AppData\Local\NonsPlayer\config.json
[22:47:00.333] [EROR] []: Config load failed: "System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at NonsPlayer.Core.Services.ConfigManager.Load() in D:\a\NonsPlayer\NonsPlayer\NonsPlayer.Core\Services\ConfigManager.cs:line 32"
[22:47:00.333] [INFO] []: Start loading adapters, current adapter path:C:\Users\Andrea-TB\AppData\Local\NonsPlayer\adapters
[22:47:00.334] [INFO] []: Try log in adapter
[22:47:00.334] [INFO] []: Start init local service
[22:47:00.337] [INFO] []: Start loading player counter
[22:47:00.339] [INFO] []: Start loading SMTC service
[22:47:00.389] [INFO] [NonsPlayer.Services.SMTCService]: Init finished
[22:47:00.668] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.HomeViewModel"
[22:47:02.500] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalViewModel"
[22:47:36.256] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalMusicLibViewModel"
[22:47:36.299] [INFO] [NonsPlayer.Cache.CacheService]: CacheService init finished
[22:47:36.299] [INFO] [NonsPlayer.Cache.CacheService]: Current cache expiration time(ms): 60000
`
