### ISSUE TITLE
[BUG]api一开就闪退，有时候不能拖动窗口，设置也会点不开点一下全屏就恢复正常

### ISSUE THREAD

**Issue by 3305932347** [Miaoyww/NonsPlayer#73]
[17:21:50.849] [INFO] []: System: Microsoft Windows NT 10.0.22631.0
[17:21:50.852] [INFO] []: Command Line: D:\NonsPlayer\app-0.5.8\NonsPlayer.dll
[17:21:50.902] [INFO] []: Start loading config, current config path:C:\Users\X\AppData\Local\NonsPlayer\config.json
[17:21:50.933] [INFO] []: Start loading adapters, current adapter path:C:\Users\X\AppData\Local\NonsPlayer\adapters
[17:21:50.934] [INFO] []: Try log in adapter
[17:21:50.934] [INFO] []: Start init local service
[17:21:50.937] [INFO] []: Start loading player counter
[17:21:50.941] [INFO] []: Start loading SMTC service
[17:21:50.992] [INFO] [NonsPlayer.Services.SMTCService]: Init finished
[17:21:51.290] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.HomeViewModel"
[17:21:54.083] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.SettingsViewModel"
[17:22:27.622] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.HomeViewModel"
[17:22:29.063] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.ExploreViewModel"
[17:22:31.101] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.PersonalCenterViewModel"
[17:22:31.953] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalViewModel"
[17:22:34.119] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.HomeViewModel"
[17:22:35.240] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.ExploreViewModel"
[17:22:37.282] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.PersonalCenterViewModel"
[17:22:39.279] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.SettingsViewModel"
[17:22:45.057] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.AdapterManagerViewModel"
[17:22:51.449] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.SettingsViewModel"
[17:25:50.275] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalViewModel"
[17:25:51.289] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalQueueViewModel"
[17:25:52.802] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalViewModel"
[17:25:53.537] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalMusicLibViewModel"
[17:25:55.279] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.LocalViewModel"
[17:25:55.651] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.PersonalCenterViewModel"
[17:25:57.451] [INFO] [NonsPlayer.Services.NavigationService]: Navigate to "NonsPlayer.ViewModels.SettingsViewModel"
[17:26:05.320] [EROR] []: App Version:0.5.8
Unhandled exception threw: System.Net.HttpListenerException (1214): 指定的网络名格式无效。
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at NonsPlayer.Core.Services.ControlService.StartAsync() in D:\a\NonsPlayer\NonsPlayer\src\NonsPlayer.Core\Services\ControlService.cs:line 170
   at NonsPlayer.Views.Pages.SettingsPage.ApiSwitch(Object sender, RoutedEventArgs e) in D:\a\NonsPlayer\NonsPlayer\src\NonsPlayer\Views\Pages\MainPages\SettingsPage.xaml.cs:line 169
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by 3305932347** [comment]
https://github.com/user-attachments/assets/310af807-82ec-4a39-8197-8c3048195e51

大佬有时候点进来还会没反应，我不知道是哪的问题

**Comment by Miaoyww** [comment]
窗口拖动问题追踪 #71

**Comment by Miaoyww** [comment]
问题出现在注释部分
当时是为了应对比赛才临时做的这一部分，现在暂时关闭Api控制功能，待后期开放。

```C#
    public ControlService()
    {
        _httpListener = new HttpListener();
        // _httpListener.Prefixes.Add($"http://192.168.101.111:8080/nons/api/{API_VERSION}/");
        _cancellationTokenSource = new CancellationTokenSource();
    }
```
